graph LR
    %% ESTILOS
    classDef silverClass fill:#e3f2fd,stroke:#1565c0,stroke-width:2px,color:#000;
    classDef goldClass fill:#fff9c4,stroke:#fbc02d,stroke-width:2px,color:#000;

    %% SILVER
    S_DEFAULT["silver_feeds.default_product_info"]:::silverClass

    %% GOLD
    G_VAR["gold_price_analysis.category_price_variability"]:::goldClass
    G_CLASS["gold_price_analysis.category_price_classification"]:::goldClass
    G_PROD["gold_price_analysis.product_price_segmentation"]:::goldClass

    %% FLUXO ETL
    S_DEFAULT -.-> G_VAR
    S_DEFAULT -.-> G_CLASS
    S_DEFAULT -.-> G_PROD